### ISSUE TITLE
Revisit permissions of VPC CNI

### ISSUE THREAD

**Issue by divergentdave** [abetterinternet/prio-server#1345]
A comment deleted in #1297 mentioned that we would prefer to grant just `AmazonEKS_CNI_Policy` to the VPC CNI addon, rather than adding that policy to the worker nodes' instance profile, and having it implicitly use that. It appears the issue was that within a fully-private network, the `sts:AssumeRole` call was failing. I'd like to take another crack at this, by first adding an [interface VPC endpoint for STS](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_sts_vpce.html), configuring the addon to use the endpoint, and then splitting up the IAM roles again.

Edit: I suppose it follows we'll also need an [interface VPC endpoint for the EC2 API](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/interface-vpc-endpoints.html) as well, to manage the VPCs.

Edit: [EKS docs](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html) say we also need endpoints for the ECR API, the ECR Docker registry, and S3.

**Comment by tgeoghegan** [comment]
I deleted that comment because it's no longer accurate: [we do create a specific role for the CNI plugin](https://github.com/abetterinternet/prio-server/blob/85a3fd446ecbc3c597c3841cd27a85613d4de081/terraform/cluster_bootstrap/modules/eks/eks.tf#L328). We also [already create the VPC endpoints for AWS APIs you describe](https://github.com/abetterinternet/prio-server/blob/85a3fd446ecbc3c597c3841cd27a85613d4de081/terraform/cluster_bootstrap/modules/eks/eks.tf#L110).
