### ISSUE TITLE
Week of 2022/02/22 deploys

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-server#1415]
Things we (may) need to deploy:

- `us-ak` in `prod-us`
- Deploy a fix for https://github.com/abetterinternet/prio-server/issues/1414

**Comment by BranLwyd** [comment]
Deploy to `staging-us`, `intl-staging` complete.

**Comment by BranLwyd** [comment]
`prod-us`, `prod-intl` have been released.

The only noteworthy thing is that due to https://github.com/abetterinternet/prio-server/commit/a907e1207e1342e7cb21bb51a7b0569f8cb96c03, there was a small window during the `prod-us` deploy where the "serviceAccountTokenCreator" role was empty. I think this would cause writes to the sum-part bucket to fail for this duration; however, given that the window was a few minutes at most, I think the standard retry windows would allow any affected work items to eventually process successfully (and indeed, nothing appears to have fallen into our DLQs).
