### ISSUE TITLE
workflow-manager: limit listing of files to recent ones

### ISSUE THREAD

**Issue by jsha** [abetterinternet/prio-server#162]
The S3 ListObjectsV2 API (https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html) has a limit of 1000 objects; presumably GS has a similar limit. When workflow-manager runs, it should construct a set of path prefixes that would match the given --max-age flag, in order to ignore stuff that is too old and get more relevant results in that 1000.

**Comment by tgeoghegan** [comment]
The 1000 object limit shouldn't be a problem since we use the paginated API for listing both S3 and GCS buckets, but we could save significant time in `workflow-manager` by ignoring old objects.

**Comment by bmw** [comment]
I looked into this a bit. As suggested by jsha, the main way to filter the returned results in both S3 and GS is to provide a prefix and only objects which match that prefix will be returned. Prefixes must be simple strings (e.g. no wildcards).

My understanding is intake file names (which is what `--max-age` is used with) start with a string like `kittens-seen/2020/10/31/20/29/b8a5579a-f984-460a-a42d-2813cbf57771` where `kittens-seen` is the aggregation ID. This means that to ignore old files like this using a prefix, we'll need to make a separate query for each aggregation ID rather than grabbing everything at once.

Additionally, we need to know the aggregation IDs. Do we know the expected aggregation IDs ahead of time and want to give those values to the workflow-manager when it launches? Alternatively, I think I could do a separate initial query making use a delimiter parameter in both GS and S3 to list the common prefixes to find the aggregation IDs in the buckets and from there construct full prefixes that take into account `--max-age`.

Based on this, do you have a preference for next steps here?

**Comment by tgeoghegan** [comment]
That's funny, we were just talking about this today! We do not know ahead of time what aggregations are supported. So, yes, we could solve this by doing an initial query as you describe.

However, we _could_ make the list of expected aggregation IDs part of the configuration of `workflow-manager`. Besides simplifying the logic needed to address the problem in this issue, it would protect us against sudden spikes in workload if our ingestor partners suddenly turn on new metrics/aggregations they are tracking. So they could upload batches in whatever aggregation they want, but they wouldn't induce any new workload for us until we explicitly instruct `workflow-manager` to start looking for them. The downside is that there would be a bit of extra ceremony before we can turn on new aggregations (ingestor parters would have to come tell us what the aggregation ID is, then we'd have to make a config change and deploy it), but in practice, that happens anyway because we probably would need to scale up the sizes of worker Kubernetes deployments and possibly node pools (as in, the VMs that make up the cluster) before ingestors can start sending more data through the system. We currently have three aggregations from Google and five from Apple, so adding one aggregation to either is a significant increase in workload, if we assume all aggregations send roughly the same volume of data through.

Maybe I'm biased towards safety and conservatism right now since we just spent the afternoon negotiating an incident in prod, but the more I think about it, the more I like the idea of requiring a data share processor to explicitly consent to new aggregations.

**Comment by tgeoghegan** [comment]
This issue has been causing some grief for NCI, and also resolving it would make it easier to set up some metrics I'm interested in reporting, so I'm going to take care of it tomorrow or maybe early next week.
