### ISSUE TITLE
workflow-manager: Add exponential backoff to retry logic implemented in #258

### ISSUE THREAD

**Issue by aaomidi** [abetterinternet/prio-server#261]
#258 implements retry logic, we should probably look into exponential backoff if we want to use that

**Comment by bmw** [comment]
It looks like the retry logic implemented in #258 is no longer used. Do we still want this?

**Comment by tgeoghegan** [comment]
I removed the usage of the retry module because the GCP SDK is documented to implement appropriate retry logic, unlike the Kubernetes API call we previously made. We should check if the same is true of the AWS SDK, and if it's not, we should wrap those calls with retries. Ideally we would also retry individual API calls, instead of retrying the whole call to `enqueueIntakeJobs` as we used to.

**Comment by bmw** [comment]
The AWS SDK is also documented to implement its own retry logic. The documentation on it is a little sparse, but https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/welcome.html says

> The SDK removes the complexity of coding directly against a web service interface. It hides a lot of the lower-level plumbing, such as authentication, request retries, and error handling. 

and https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config includes options for overriding the default retry logic.

With this being handled inside the SDKs, I think we could close this issue and delete the custom retry module. There's always git history, however, you all may prefer to keep that module around in case there's a need for it in the future as well as keeping this issue as a reminder that the module does not implement exponential backoff.

**Comment by tgeoghegan** [comment]
I agree with your analysis here. The retry module was deleted in #324 in favor of a dependency that has some fancier features like exponential backoff, so I don't think there's anything left to do here.
