### ISSUE TITLE
[schema] aggregation-share/sum-part has incorrect cardinality of sum and batch_uuid

### ISSUE THREAD

**Issue by yuriks** [abetterinternet/prio-server#3]
In the original protobuf schema defined in the [IDL document](https://docs.google.com/document/d/1L06dpE7OcC4CXho2UswrfHrnWKtbA9aSSmO_5o7Ku6I/edit), `PrioSumPart` contained a single `bytes value_sum` field, and a repeated `batch_uuid` list. The `batch_uuid` list represents the uuids of all of the batches (tracing back to the ingestor) that participated in this aggregation.

At some point in the conversion to Avro, this got flipped and the current schema now has only a single `batch_uuid`, but an array of `sums`.

Not only does this not let us properly represent the `batch_uuid`s when we do the final multi-batch reduction sum, the `sums` array will also always contain only one value (because all aggregations we'll do always produce a single output sum per file, both the per-batch sum, and the overall sum for a given time range), so this seems like an oversight and should be fixed to match the intent of the original schema.

**Comment by tlepoint** [comment]
Actually, the `sums` array needs to be an array, because the sum is done over a vector containing n bins. We can choose the terminology that you prefer (one `sum` of a vector, or many individual `sums`, the current avro file choosing the latter formulation). In the original proto schema, `sum` was represented as bytes (assuming proper serialization): I modified this to be `int64` to be consistent with the `f_r`, `g_r`, `h_r`, and `r_pit` terms.

Thanks for catching the error for the `batch_uuid`, this indeed should be an array. I may have been thrown off by the comment above the `batch_uuid` field.

**Comment by tgeoghegan** [comment]
You're quite right @tlepoint, and Yuri and I realized as much last Friday, but failed to say as much in this issue. I think what I currently have in #2 is consistent with what you're saying.

**Comment by tgeoghegan** [comment]
Addressed in #2. Please file a new issue for further schema amendments, referencing this one if necessary.
