### ISSUE TITLE
Document that raw message delivery should be used for SNS/SQS task queues

### ISSUE THREAD

**Issue by hostirosti** [abetterinternet/prio-server#328]
https://github.com/abetterinternet/prio-server/blob/3ac50ce2d81001b9bb704175a977cac88d2d4569/facilitator/src/task/sqs.rs#L97

Message format:
```
{
  "Type" : "Notification",
  "MessageId" : "cedae512-08bb-5558-aa03-bd91c7c7656d",
  "TopicArn" : "arn:aws:sns:us-east-1:994058661178:narnia-ta-ta-ta-g-enpa-intake",
  "Message" : "{\\"aggregation-id\\":\\"PeriodicExposureNotification-v1\\",\\"batch-id\\":\\"d479b2cf-e6d6-3ec4-b924-862df1a7f40b\\",\\"date\\":\\"2021/01/21/19/00\\"}",
  "Timestamp" : "2021-01-21T18:51:40.606Z",
  "SignatureVersion" : "1",
  "Signature" : "iAFu88K7dmctdxQQfkk0PrzDjRYNJ4WZpeU0GICBt3HzouB2Leq2hdQ5VNc3xMqWN7FVHeelaJtjuoZtA+menh17On1+zfs9HK+K0FpfXwmyTMKWcqGQf1QxseCfstETXp9+yOHXaDGkVYqbTq7B59FfJrg0KlYPVudZVXko4rSWsOwmAC5ZWS/ayJHKvx3DCTEtrizkZDCWn0so2i7ubKacr4QyKx23S6bwJ6gnm4Spbazqz/4OZJTUGHUILbD9LTe7fCztzbeAY1zBvzIbZICbfThy5hLmlabp6KGZEtLyTOewmrS3Qpt6LqmibxgxMFL+HrYdWETObR4lWNTkYw==",
  "SigningCertURL" : "https://sns.us-east-1.amazonaws.com/SimpleNotificationService-010a507c1833636cd94bdb98bd93083a.pem",
  "UnsubscribeURL" : "https://sns.us-east-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:994058661178:narnia-ta-ta-ta-g-enpa-intake:5bcba351-a459-4288-b512-5a7adf1b9237"
}
```

The Task is in `Message`.

**Comment by tgeoghegan** [comment]
`facilitator` was expecting the message received from SQS to just be the JSON object in the `Message` field of the object Robert pasted in the description. It turns out that by default, messages published to SQS from an SNS topic get wrapped in SNS metadata. We were able to work around this by enabling [raw message delivery](https://docs.aws.amazon.com/sns/latest/dg/sns-large-payload-raw-message-delivery.html), which configures SNS to avoid adding the metadata wrapper. Once that was done, the messages were in the expected format and things worked normally. I think the remaining thing to do here is to document that raw message delivery should be used when setting up SNS/SQS for `prio-server` task queues. Retitling accordingly.
